"""create batch table

Revision ID: 2b4cf6fc0424
Revises: a53ad27be4f1
Create Date: 2026-03-12 21:37:07.108341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b4cf6fc0424'
down_revision: Union[str, Sequence[str], None] = 'a53ad27be4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_name'), 'batches', ['name'], unique=False)
    op.create_table('batch_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('allocated_by', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'user_id', name='unique_batch_user_allocation')
    )
    op.create_index(op.f('ix_batch_allocations_batch_id'), 'batch_allocations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_allocations_user_id'), 'batch_allocations', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_batch_id'), 'tasks', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_batch_id'), table_name='tasks')
    op.drop_column('tasks', 'batch_id')
    op.drop_index(op.f('ix_batch_allocations_user_id'), table_name='batch_allocations')
    op.drop_index(op.f('ix_batch_allocations_batch_id'), table_name='batch_allocations')
    op.drop_table('batch_allocations')
    op.drop_index(op.f('ix_batches_name'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
