"""add cloud_devices table

Revision ID: c6c55efd4bea
Revises: f29f0ce854e8
Create Date: 2026-01-16 10:56:28.222468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6c55efd4bea'
down_revision: Union[str, Sequence[str], None] = 'f29f0ce854e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('pod_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'pod_id', name='unique_product_pod')
    )
    op.create_index(op.f('ix_cloud_devices_is_active'), 'cloud_devices', ['is_active'], unique=False)
    op.create_index(op.f('ix_cloud_devices_pod_id'), 'cloud_devices', ['pod_id'], unique=False)
    op.create_index(op.f('ix_cloud_devices_product_id'), 'cloud_devices', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_devices_product_id'), table_name='cloud_devices')
    op.drop_index(op.f('ix_cloud_devices_pod_id'), table_name='cloud_devices')
    op.drop_index(op.f('ix_cloud_devices_is_active'), table_name='cloud_devices')
    op.drop_table('cloud_devices')
    # ### end Alembic commands ###
